# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(832, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QWidget(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(0, 0, 831, 571))
        self.Logo.setStyleSheet("#Logo{\n" "background-color:#8C52FF;\n" "}")
        self.Logo.setObjectName("Logo")
        self.Signin = QtWidgets.QWidget(self.Logo)
        self.Signin.setGeometry(QtCore.QRect(415, 0, 421, 571))
        self.Signin.setStyleSheet(
            "#Signin{\n"
            "background-color:white;\n"
            "}\n"
            "QLineEdit#Password,\n"
            "QLineEdit#Username{\n"
            "border: 1px solid #7B7878;\n"
            "border-radius:5px;\n"
            "padding:8px;\n"
            "font-size:14px;\n"
            "}\n"
            "QLineEdit#Password:focus,\n"
            "QLineEdit#Username:focus{\n"
            "border-color:#8C52FF;\n"
            "}\n"
            "\n"
            ""
        )
        self.Signin.setObjectName("Signin")
        self.label = QtWidgets.QLabel(self.Signin)
        self.label.setGeometry(QtCore.QRect(40, 130, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Username = QtWidgets.QLineEdit(self.Signin)
        self.Username.setGeometry(QtCore.QRect(40, 210, 331, 41))
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLineEdit(self.Signin)
        self.Password.setGeometry(QtCore.QRect(40, 280, 331, 41))
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.SigninBtn = QtWidgets.QPushButton(self.Signin)
        self.SigninBtn.setGeometry(QtCore.QRect(240, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SigninBtn.setFont(font)
        self.SigninBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SigninBtn.setStyleSheet(
            "#SigninBtn{\n"
            "background-color:#8C52FF;\n"
            "color : white;\n"
            "border:none;\n"
            "border-radius:5px;\n"
            "}\n"
            "#SigninBtn:hover{\n"
            "background-color:white;\n"
            "border: 1px solid #8C52FF;\n"
            "color:#8C52FF;\n"
            "}"
        )
        self.SigninBtn.setObjectName("SigninBtn")
        self.SignupBtn = QtWidgets.QPushButton(self.Signin)
        self.SignupBtn.setGeometry(QtCore.QRect(50, 490, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.SignupBtn.setFont(font)
        self.SignupBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignupBtn.setStyleSheet(
            "#SignupBtn{\n"
            "border:1px solid #8C52FF;\n"
            "border-radius: 5px;\n"
            "color:#8C52FF;\n"
            "}\n"
            "#SignupBtn:hover{\n"
            "background-color:#F1EDED;\n"
            "}"
        )
        self.SignupBtn.setObjectName("SignupBtn")
        self.ForgetBtn = QtWidgets.QPushButton(self.Signin)
        self.ForgetBtn.setGeometry(QtCore.QRect(40, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ForgetBtn.setFont(font)
        self.ForgetBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ForgetBtn.setStyleSheet(
            "#ForgetBtn{\n"
            "border:none;\n"
            "}\n"
            "#ForgetBtn:hover{\n"
            "text-decoration: underline;\n"
            "}"
        )
        self.ForgetBtn.setObjectName("ForgetBtn")
        self.logo_pic = QtWidgets.QLabel(self.Logo)
        self.logo_pic.setGeometry(QtCore.QRect(50, 90, 351, 371))
        self.logo_pic.setStyleSheet("image:url(:/newPrefix/LifeSync.png)")
        self.logo_pic.setText("")
        self.logo_pic.setObjectName("logo_pic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" color:#333333;">Sign in</span></p></body></html>',
            )
        )
        self.Username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.Password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.SigninBtn.setText(_translate("MainWindow", "Sign in"))
        self.SignupBtn.setText(
            _translate("MainWindow", "Don't have an account? Sign up")
        )
        self.ForgetBtn.setText(_translate("MainWindow", "Forgot Password?"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Login()
    ui.setupUi(MainWindow)
    sys.exit(app.exec_())
